# Generated by Django 3.1.5 on 2021-02-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='orderplaced_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
