# Generated by Django 3.1.5 on 2021-02-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210205_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('packed', 'packed'), ('On the Way', 'On the Way'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
    ]
